---
name: POE-Component-WWW-Google-PageRank
version: 0.03
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  A non-blocking wrapper for
  L<WWW::Google::PageRank>
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Filter::Line: 1.192
  POE::Filter::Reference: 1.2187
  POE::Wheel::Run: 1.2179
  WWW::Google::PageRank: 0.14
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::Google::PageRank:
    file: lib/POE/Component/WWW/Google/PageRank.pm
    version: 0.03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
